<?xml version="1.0" encoding="ISO-8859-1"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.dbunit</groupId>
  <artifactId>dbunit-maven-plugin</artifactId>
  <version>1.3.1-SNAPSHOT</version>
  <packaging>maven-plugin</packaging>

  <name>dbUnit Maven Plugin</name>
  <url>http://dbunit.sourceforge.net/dbunit-maven-plugin/</url>
  <inceptionYear>2006</inceptionYear>
  <description>
    Use this plugin to invoke dbUnit utilities.
  </description>

  <licenses>
    <license>
      <name>GNU Lesser General Public License, Version 2.1</name>
      <url>http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <properties>
    <!-- Maven configuration -->
    <project.build.outputTimestamp>2026-05-24T02:50:01Z</project.build.outputTimestamp>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <project.scm.id>github</project.scm.id>

    <!-- General values -->
    <compileSource>1.8</compileSource>
    <mavenVersion>3.0.4</mavenVersion>

    <!-- Framework versions -->
    <antVersion>1.6.5</antVersion>
    <assertjVersion>3.27.7</assertjVersion>
    <!-- TODO this needed for plugin? -->
    <commonsCollectionsVersion>3.2.2</commonsCollectionsVersion>
    <!-- always set to minimum version this plugin needs for its features -->
    <dbunitVersion>3.1.0</dbunitVersion>
    <hsqldbVersion>1.8.0.10</hsqldbVersion>
    <junitVersion>6.1.0</junitVersion>
    <mavenArtifactVersion>3.9.16</mavenArtifactVersion>
    <mavenModelVersion>3.9.16</mavenModelVersion>
    <mavenPluginApiVersion>3.9.16</mavenPluginApiVersion>
    <mavenSettingsVersion>3.9.16</mavenSettingsVersion>
    <slf4jVersion>2.0.18</slf4jVersion>

    <!-- Database driver versions -->
    <hsqldbDriverVersion>1.8.0.7</hsqldbDriverVersion>

    <!-- Maven plugin versions -->
    <asciidoctorMavenPluginVersion>3.2.0</asciidoctorMavenPluginVersion>
    <centralPublishingMavenPluginVersion>0.10.0</centralPublishingMavenPluginVersion>
    <mavenChangesPluginVersion>3.0.0-M3</mavenChangesPluginVersion>
    <compilerPluginVersion>3.15.0</compilerPluginVersion>
    <gpgPluginVersion>3.2.8</gpgPluginVersion>
    <jarPluginVersion>3.5.0</jarPluginVersion>
    <javadocPluginVersion>3.12.0</javadocPluginVersion>
    <mavenInvokerPluginVersion>3.10.1</mavenInvokerPluginVersion>
    <mavenPluginPluginVersion>3.15.2</mavenPluginPluginVersion>
    <projectInfoReportsPluginVersion>3.9.0</projectInfoReportsPluginVersion>
    <sitePluginVersion>3.22.0</sitePluginVersion>
    <sourcePluginVersion>3.4.0</sourcePluginVersion>
    <versionsMavenPluginVersion>2.21.0</versionsMavenPluginVersion>

    <!-- Other versions -->
    <wagonSshVersion>3.5.3</wagonSshVersion>
  </properties>

  <scm>
    <connection>scm:git:https://github.com/dbunit/dbunit-maven-plugin.git</connection>
    <developerConnection>scm:git:git@github.com:dbunit/dbunit-maven-plugin.git</developerConnection>
    <url>https://github.com/dbunit/dbunit-maven-plugin.git</url>
    <tag>plugin-1.3.0</tag>
  </scm>
  <issueManagement>
    <system>github</system>
    <url>https://github.com/dbunit/dbunit-maven-plugin/issues</url>
  </issueManagement>
  <ciManagement>
    <system>GitHub Actions</system>
    <url>https://github.com/dbunit/dbunit-maven-plugin/actions</url>
  </ciManagement>

  <prerequisites>
    <maven>2.0</maven>
  </prerequisites>

  <developers>
    <developer>
      <name>Jeff Jensen</name>
      <id>jeffjensen</id>
      <email>jeffjensen@users.sourceforge.net</email>
      <roles>
        <role>Java Developer (active)</role>
      </roles>
    </developer>
    <developer>
      <id>topping</id>
      <name>Brian Topping</name>
      <email>topping@codehaus.org</email>
      <roles>
        <role>Java Developer</role>
      </roles>
      <timezone>+8</timezone>
    </developer>
    <developer>
      <id>dtran</id>
      <name>Dan Tran</name>
      <email>dantran@apache.org</email>
      <roles>
        <role>Java Developer</role>
      </roles>
    </developer>
    <developer>
      <id>david</id>
      <name>David J. M. Karlsen</name>
      <email>david@codehaus.org</email>
      <organization>codehaus.org</organization>
      <organizationUrl>http://www.codehaus.org</organizationUrl>
      <roles>
        <role>Java Developer</role>
      </roles>
      <timezone>1</timezone>
      <url>http://www.davidkarlsen.com</url>
    </developer>
  </developers>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <version>${assertjVersion}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>${junitVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.junit.platform</groupId>
        <artifactId>junit-platform-launcher</artifactId>
        <version>${junitVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.junit.platform</groupId>
        <artifactId>junit-platform-suite-engine</artifactId>
        <version>${junitVersion}</version>
      </dependency>
      <dependency>
        <groupId>hsqldb</groupId>
        <artifactId>hsqldb</artifactId>
        <version>${hsqldbVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.dbunit</groupId>
        <artifactId>dbunit</artifactId>
        <version>${dbunitVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${slf4jVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>${slf4jVersion}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>ant</groupId>
        <artifactId>ant</artifactId>
        <version>${antVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.maven</groupId>
        <artifactId>maven-artifact</artifactId>
        <version>${mavenArtifactVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.maven</groupId>
        <artifactId>maven-model</artifactId>
        <version>${mavenModelVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.maven</groupId>
        <artifactId>maven-plugin-api</artifactId>
        <version>${mavenPluginApiVersion}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.maven.plugin-tools</groupId>
        <artifactId>maven-plugin-annotations</artifactId>
        <version>${mavenPluginPluginVersion}</version>
        <scope>provided</scope>
      </dependency>
      <dependency>
        <groupId>org.apache.maven</groupId>
        <artifactId>maven-settings</artifactId>
        <version>${mavenSettingsVersion}</version>
      </dependency>
      <dependency>
        <groupId>commons-collections</groupId>
        <artifactId>commons-collections</artifactId>
        <version>${commonsCollectionsVersion}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.dbunit</groupId>
      <artifactId>dbunit</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ant</groupId>
      <artifactId>ant</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-artifact</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-model</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-plugin-api</artifactId>
      <!-- FIXME resolve other updates and then enable this to resolve build warning -->
<!--      <scope>provided</scope>-->
    </dependency>
    <dependency>
      <groupId>org.apache.maven.plugin-tools</groupId>
      <artifactId>maven-plugin-annotations</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-settings</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>commons-collections</groupId>
      <artifactId>commons-collections</artifactId>
    </dependency>
  </dependencies>

  <build>
    <defaultGoal>install</defaultGoal>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.sonatype.central</groupId>
          <artifactId>central-publishing-maven-plugin</artifactId>
          <version>${centralPublishingMavenPluginVersion}</version>
          <extensions>true</extensions>
          <configuration>
            <publishingServerId>central-publish</publishingServerId>
            <autoPublish>true</autoPublish>
            <waitUntil>published</waitUntil>
            <deploymentName>dbunit-core</deploymentName>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>${gpgPluginVersion}</version>
          <executions>
            <execution>
              <id>sign-artifacts</id>
              <phase>verify</phase>
              <goals>
                <goal>sign</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${jarPluginVersion}</version>
          <configuration>
            <includes>
              <include>/LICENSE.txt</include>
              <include>**</include>
            </includes>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>${javadocPluginVersion}</version>
          <!--
            FIXME remove -Xdoclint:none after JavaDoc cleanup.
          -->
          <configuration>
            <additionalparam>-Xdoclint:none</additionalparam>
            <doclint>none</doclint>
          </configuration>
          <executions>
            <execution>
              <id>attach-javadocs</id>
              <goals>
                <goal>jar</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-plugin-plugin</artifactId>
          <version>${mavenPluginPluginVersion}</version>
          <executions>
            <execution>
              <id>default-descriptor</id>
              <goals>
                <goal>descriptor</goal>
              </goals>
              <phase>process-classes</phase>
            </execution>
            <execution>
              <id>help-mojo</id>
              <goals>
                <goal>helpmojo</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>${sitePluginVersion}</version>
          <configuration>
            <relativizeSiteLinks>false</relativizeSiteLinks>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.wagon</groupId>
              <artifactId>wagon-ssh</artifactId>
              <version>${wagonSshVersion}</version>
            </dependency>
            <dependency>
              <groupId>org.asciidoctor</groupId>
              <artifactId>asciidoctor-parser-doxia-module</artifactId>
              <version>${asciidoctorMavenPluginVersion}</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>${sourcePluginVersion}</version>
          <executions>
            <execution>
              <id>attach-sources</id>
              <phase>verify</phase>
              <goals>
                <goal>jar-no-fork</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>${versionsMavenPluginVersion}</version>
          <configuration>
            <rulesUri>file:///${project.basedir}/versions-maven-plugin-rules.xml</rulesUri>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <!--
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-docck-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
       -->

      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compilerPluginVersion}</version>
        <configuration>
          <source>${compileSource}</source>
          <target>${compileSource}</target>
          <release>8</release>
          <compilerVersion>${compileSource}</compilerVersion>
          <encoding>${project.build.sourceEncoding}</encoding>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-invoker-plugin</artifactId>
        <version>${mavenInvokerPluginVersion}</version>
        <configuration>
          <debug>true</debug>
          <projectsDirectory>src/example</projectsDirectory>
          <localRepositoryPath>${project.build.directory}/it-repo</localRepositoryPath>
          <pomIncludes>
            <pomInclude>**/pom.xml</pomInclude>
          </pomIncludes>
          <cloneProjectsTo>${project.build.directory}/it</cloneProjectsTo>
          <settingsFile>src/it/settings.xml</settingsFile>
        </configuration>
        <executions>
          <execution>
            <id>integration-test</id>
            <goals>
              <goal>install</goal>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-changes-plugin</artifactId>
        <version>${mavenChangesPluginVersion}</version>
        <configuration>
          <smtpHost>localhost</smtpHost>
          <smtpPort implementation="java.lang.Integer">25</smtpPort>
          <introduction>If you are reading this, the maintainer forgot to describe what's the purpose of this release!!!</introduction>
          <toAddresses>
            <toAddress implementation="java.lang.String">dbunit-developer@lists.sourceforge.net</toAddress>
            <toAddress implementation="java.lang.String">dbunit-user@lists.sourceforge.net</toAddress>
          </toAddresses>
          <urlDownload>http://dbunit.sourceforge.net/repos.html</urlDownload>
          <issueLinkTemplatePerSystem>
            <sftickets><![CDATA[https://sourceforge.net/p/dbunit/plugintickets/%ISSUE%]]></sftickets>
            <sfmerges><![CDATA[https://sourceforge.net/p/dbunit/dbunit-maven-plugin/merge-requests/%ISSUE%]]></sfmerges>
          </issueLinkTemplatePerSystem>
        </configuration>
        <reportSets>
          <reportSet>
            <reports>
              <report>changes</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-plugin-plugin</artifactId>
        <version>${mavenPluginPluginVersion}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-plugin-report-plugin</artifactId>
        <version>${mavenPluginPluginVersion}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-project-info-reports-plugin</artifactId>
        <version>${projectInfoReportsPluginVersion}</version>
      </plugin>
    </plugins>
  </reporting>

  <profiles>
    <profile>
      <id>release</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
