= Releasing

== Overview

The following steps describe how to release the dbUnit Maven Plugin.
While the Maven release plugin automates steps such as version change, commit, and deploy,
the dbUnit Maven Plugin has manual file information update steps that are outside of its scope.

While the below steps do not use the Maven release plugin,
you can use it by performing the manual file edits first then running the release plugin steps.

== Release Steps

. Update pom.xml

.. Set version to release version

.. Set `<project.build.outputTimestamp>` property to the release timestamp, typically today's date with midnight time

. Update changes.xml

.. Update release version

.. Set release date to today

. Commit files "Prep release x.y.z"

. Tag the commit; prefix release number with "plugin-"

. Push the commit

. Build and deploy the release
+
----
mvnw clean
mvnw deploy -Prelease
----

. Build and deploy the site

.. Build site:
+
----
mvnw site
----

.. Review site results for issues and correct as necessary

.. Publish: 
Commits to master automatically build the site and publish to GitHub pages.

*** Historical: Deploy to SourceForge;
reference how-to:
link:http://maven.apache.org/plugins/maven-site-plugin/examples/site-deploy-to-sourceforge.net.html[Deploying to sourceforge.net]
+
----
ssh -t sf-username,dbunit@shell.sourceforge.net create
mvnw site:deploy
----

. Post Announcement Discussion https://github.com/dbunit/dbunit-maven-plugin/discussions/categories/announcements
.. Consider using the changes plugin's announcement-generate goal 
+
[source,bash]
----
mvnw changes:announcement-generate -Dchanges.version=theNewVersion
----
+
Review and adjust the text as desired before using.

. Prepare next release in SCM
.. Update pom.xml
... Update to SNAPSHOT version
.. Update src/example/pom.xml
... Update to match new plugin (SNAPSHOT) version
.. Update changes.xml with new SNAPSHOT entry
