name: Build any branch

on: [push, pull_request]

env:
  MAVEN_COMMAND: ./mvnw
  MAVEN_CLI_COMMON: "-e -B"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/jdk-setup
    - name: Compile and run unit tests
      run: ${{ env.MAVEN_COMMAND }} ${{ env.MAVEN_CLI_COMMON }} clean test
    - name: Submit dependencies to GitHub
      if: github.actor != 'dependabot[bot]'
      uses: advanced-security/maven-dependency-submission-action@v5
    - name: Upload target directory for reuse
      uses: actions/upload-artifact@v7
      with:
        name: target-directory
        path: target/
        retention-days: 11
